import type { Metadata } from "next";
import "../../presentation/styles/root.scss";
import style from "../../presentation/styles/layout-dashboard.module.scss";
import { Sidebar } from "@/presentation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "#fff"
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={`${style.layout} min-h-screen flex`}>
          <Sidebar />
          <div className={`${style.content}`}>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
